### PR TITLE
Fix error and add example code to README

### PR DESCRIPTION
**Pull request by BGR360**
Changed billboards to billboards.getData() and added example code for a minimal controller.

### CODE REVIEW

**Comment by bipol** [comment]
I also discovered that I have an example repository to demonstrate some of the changes I made back then... https://github.com/bipol/ac-angular-cesium-example/tree/master/src

**Comment by BGR360** [comment]
Can you add that link to the readme and merge the request?

**Comment by BGR360** [comment]
As a side note, my current job requires me to use a lot of Cesium, and I would love to regularly use this library moving forward. That being said, I'd be more than happy to take over as a maintainer/developer. What are your thoughts?

**Comment by bipol** [comment]
@BGR360 I'd love to have you as a maintainer, but unfortunately I don't have those permissions.  Pinging @netanelgilad for that.

**Comment by bipol** [comment]
@BGR360 also, could you add that change to your fork, just to keep all of it consolidated to this PR?

**Comment by BGR360** [comment]
Done

**Comment by bipol** [comment]
Cool!

**Pull request merged**
