### PR TITLE
Add Cesium as Bower dependency

### PR DESCRIPTION
**Pull request by BGR360**
GitHub user @mixxen provides Cesium as a bower dependency and keeps it relatively up-to-date. I've added it as a dependency in `bower.json` to ease development for the client.

See https://github.com/mixxen/cesiumjs

### CODE REVIEW

**Comment by bipol** [comment]
Looks good to me!

**Comment by BGR360** [comment]
Do we create a new version? What's the procedure in terms of the bower repository?

**Comment by bipol** [comment]
Yup, I believe we'd create a new release on Github, which would automatically sync up with bower.

**Comment by BGR360** [comment]
Ok, we should do that after we process all the pull requests / issues i made today, right?

**Comment by bipol** [comment]
@BGR360 yup, I think that would be the best time to do it.

**Pull request merged**
